name = "kakao"
license = "MIT"
licenselink = "https://github.com/pfitzseb/kakao/blob/master/LICENSE"
homepage = "https://github.com/pfitzseb/kakao/"
tags = ["clean", "fast", "responsive", "typography"]
features = ["flexible", "fast", "highlights", "progressive images", "disqus"]
min_version = 0.20.2

[author]
    name = "Sebastian Pfitzner"
    homepage = "https://github.com/pfitzseb"

[original]
    name = "Nishanth Shanmugham"
    homepage = "https://github.com/nishanths"
    repo = "https://www.github.com/nishanths/cocoa-hugo-theme"
